issues:
  max-issues-per-linter: 0
  max-same-issues: 50
  exclude-rules:
    - source: "(noinspection|TODO)"
      linters: [godot]
    - source: "//noinspection"
      linters: [gocritic]
    - path: "_test\\.go"
      linters:
        - bodyclose
        - dupl
        - errcheck
        - funlen
        - goconst
        - gosec
        - noctx
        - wrapcheck
output:
  formats:
    - format: colored-tab
      path: stderr
  print-issued-lines: false
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter
    - severity
    - file

linters-settings:
  cyclop:
    max-complexity: 20
    package-average: 10.0

  depguard:
    rules:
      "deprecated":
        files: ["$all"]
        deny:
          - pkg: "github.com/golang/protobuf"
            desc: "Use google.golang.org/protobuf instead"
          - pkg: "github.com/satori/go.uuid"
            desc: "Use github.com/google/uuid instead"
      "non-test files":
        files: ["!$test"]
        deny:
          - pkg: "math/rand$"
            desc: "Use math/rand/v2 instead"
      "non-main files":
        files: ["!**/main.go"]
        deny:
          - pkg: "log$"
            desc: "Use log/slog instead"

  dupl:
    threshold: 200

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    check: ["switch", "map"]

  funlen:
    lines: 100
    statements: 50
    ignore-comments: true

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - importShadow
      - hugeParam
      - rangeExprCopy
      - rangeValCopy

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  nakedret:
    max-func-lines: 0

  nolintlint:
    allow-no-explanation: [funlen, gocognit, lll]
    require-explanation: false
    require-specific: true

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(

run:
  issues-exit-code: 1

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wrapcheck
