# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/cursor-rules/main.go
    id: "cursor-rules"
    binary: cursor-rules
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

brews:
  - name: cursor-rules
    homepage: "https://github.com/fireharp/cursor-rules"
    description: "CLI tool to help initialize and manage Cursor Editor rules for your projects"
    license: "MIT"

    # Repository to push the generated files to
    tap:
      owner: fireharp
      name: homebrew-tap

    # Git author used to commit to the repository
    commit_author:
      name: goreleaserbot
      email: goreleaser@fireharp.dev

    # Folder inside the repository
    folder: Formula

    # A more detailed description of the tool
    caveats: "Run cursor-rules in your project directory to set up Cursor Editor rules"

    # Test block to verify the installation
    test: |
      system "#{bin}/cursor-rules --version"

    # Install instructions
    install: |
      bin.install "cursor-rules"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
