version: '3'

vars:
  BINARY: cursor-rules
  BUILD_DIR: ./bin
  MAIN_PKG: ./cmd/cursor-rules
  VERSION: 0.1.5

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the cursor-rules binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -v -o {{.BUILD_DIR}}/{{.BINARY}} {{.MAIN_PKG}}

  run:
    desc: Run the cursor-rules application
    deps: [build]
    cmds:
      - ./{{.BUILD_DIR}}/{{.BINARY}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  install:
    desc: Install the cursor-rules binary
    deps: [build]
    cmds:
      - cp {{.BUILD_DIR}}/{{.BINARY}} $GOPATH/bin/
