name: Release with GoReleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  # Required for Homebrew tap repository updates
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Run tests
        run: cd go-claude && go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: go-claude
        env:
          # This token needs to have access to the homebrew-tap repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
