name: Release with GoReleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  # Required for Homebrew tap repository updates
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: true

      - name: Run tests
        run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2" # This specifies to use latest v2.x.x of GoReleaser
          args: release --clean
        env:
          # Use a PAT with access to the homebrew-tap repository
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
